### ISSUE TITLE
Create handouts for event mentors

### ISSUE THREAD

**Issue by dannyverp** [takeaway/hacktoberfest#1]
During the event, there are several Takeaway devs that will be helping participants create successful PR/MRs.

To make their job easier (and keep things consistent) we need to create a readout/handout the mentors can use.

## Deliverables

- A printed-out version for each mentor
- A web version of the printout (available https://takeaway.technology/hacktoberfest/handout)

**Comment by Potherca** [comment]
Just of the top of my head, in random order, here are some of the topics we might want to have on our checklist:

- Do you know what "open-source" means?
- Do you know what Github.com is?
- Do you know what a merge request is?
- Do you have an account on Github?
- Do you know where you could open a merge request?
- Do you know how to create a "fork"
- Do you know what version control is?
- Are you familiar with git?
- Can you "clone" a remote git repository to your local machine?
- Have you got an editor to make local changes?
- Can you commit your local changes and push them to the remote?

And, finally, open that PR!
